### ISSUE TITLE
Network Error on Search

### ISSUE THREAD

**Issue by flipsimon** [arso-project/sonar#28]
When starting sonar with ./sonar start --dev, I get an error when searching in an island. However, the error doesn't occur when starting server and ui separately.

```
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: Child process died: 101
    at ChildProcess.<anonymous> (sonar/sonar-dat/node_modules/@arso-project/sonar-tantivy/src-nodejs/rpc.js:30:45)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:321:20)
    at Pipe.<anonymous> (net.js:668:12)
Emitted 'error' event on IndexCatalog instance at:
    at RpcPipe.<anonymous> (sonar/sonar-dat/node_modules/@arso-project/sonar-tantivy/src-nodejs/catalog.js:25:39)
    at RpcPipe.emit (events.js:333:22)
    at ChildProcess.<anonymous> (sonar/sonar-dat/node_modules/@arso-project/sonar-tantivy/src-nodejs/rpc.js:30:31)
    at ChildProcess.emit (events.js:321:20)
    [... lines matching original stack trace ...]
    at Pipe.<anonymous> (net.js:668:12)
```

**Comment by Frando** [comment]
This error occurs if sonar-tantivy is not found or crashes. We should have a better error message here.
