### ISSUE TITLE
Server crashes without data in put_schema

### ISSUE THREAD

**Issue by dryptomim** [arso-project/sonar#4]
i've build a HTTP-Request with python 
if i send this request without data, i get this error:
## Request
` req: {
       "method": "PUT",
       "url": "/api/default/schema/example_schema",
       "hostname": "localhost:9191",
       "remoteAddress": "127.0.0.1",
       "remotePort": 40140
     }`
  
## Error
```
 sonar-project/sonar/sonar-dat/node_modules/hyper-content-db/index.js:482
       properties: schema.properties
                          ^
 TypeError: Cannot read property 'properties' of undefined
     at HyperContentDB._encodeSchema (sonar-project/sonar/sonar-dat/node_modules/hyper-content-db/index.js:482:26)
     at sonar-project/sonar/sonar-dat/node_modules/hyper-content-db/index.js:446:26
     at sonar-project/sonar/sonar-dat/node_modules/hyper-content-db/index.js:429:9
     at apply (sonar-project/sonar/sonar-dat/node_modules/thunky/index.js:44:12)
     at processTicksAndRejections (internal/process/task_queues.js:77:11)
'
```

**Comment by dryptomim** [comment]
fixed
